// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uprgbkzhmjihouzhtapb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwcmdia3pobWppaG91emh0YXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzk4OTEsImV4cCI6MjA2MTY1NTg5MX0.C6vxq0l_WGt-8cM_GAUnSMP69v96S8ZVlQ3lN_9m-bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);